### ISSUE TITLE
[EPIC] Flow Contract Migration Manager

### ISSUE THREAD

**Issue by gregsantos** [onflow/flow-cli#1375]
### Overview

The FCMM CLI tool is designed to facilitate the staging, management, and inquiry of smart contract upgrades in preparation for the network-wide migration to Cadence 1.0. It aims to simplify the process for developers to stage their contracts before breaking changes occur. It’s a set of additional commands within Flow CLI. This is the P0 interface for developers to stage.

[Staging CLI PRD](https://www.notion.so/dapperlabs/Staging-CLI-PRD-022296c2871649ce9fcf8af6e1607d89)
```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flow-cli/issues/1387
- [ ] https://github.com/onflow/flow-cli/issues/1386
- [ ] https://github.com/onflow/flow-cli/issues/1397
- [ ] https://github.com/onflow/flow-cli/issues/1398
- [ ] https://github.com/onflow/flow-cli/issues/1399
```
