### ISSUE TITLE
[EPIC] CLI setup command

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-cli#707]
The setup super-command will create a new project for a user containing all the content he needs to start development. 

The user will be able to run the `flow setup` command, which will create:
- `contracts` folder, where they should be putting all of his contracts
- `scripts` folder, where they should be putting all the scripts
- `transactions` folder where they should be putting all txs
- `tests` folder containing cadence tests 
- `flow.json` a base configuration file
- `Readme.md` a file explaining the development process and commands they can use going forward

This should look like:
![Image](https://user-images.githubusercontent.com/75445744/203518371-d5e569d1-27e7-4579-b425-eca13da43127.png)

Running the flow setup command will also prompt the user if he wants to choose a scaffold from which to start their project. 

This should look something like this:
```
> flow setup

Chose a scaffold to start your project:
> Empty
   React.js with FCL

```

- [ ] https://github.com/onflow/flow-cli/issues/708
- [ ] https://github.com/onflow/flow-cli/issues/709
- [ ] [Implement the React FCL scaffold](https://github.com/chasefleming/fcl-next-scaffold)
